import Head from "next/head";
import Nav from "../components/nav";
import Application from "../components/application";
// import Benefits from "../components/benefits";
// import Features from "../components/features";
// import Planned from "../components/planned";
// import Demo from "../components/demo";
import Footer from "../components/footer";
import styles from "../styles/Home.module.scss";
import About from "../components/about";
import Principles from "../components/principles";
import Projects from "../components/projects";
import Clients from "../components/clients";
import Why from "../components/why";
import Services from "../components/services";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ИнструментЦентр</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.wrapper}>
        <Nav></Nav>
        <About></About>
        <Why></Why>
        <Principles></Principles>
        <Services></Services>
        <Projects></Projects>
        <Clients></Clients>
        <Application></Application>
        <Footer></Footer>
      </div>

      {/* <Header></Header>
      <Benefits></Benefits>
      <Features></Features>
      <Planned></Planned>
      <Demo></Demo>
      <Footer></Footer> */}
    </div>
  );
}
