import React, { useState, useEffect } from "react";
import Loading from "../components/loading";
import Head from "next/head";
import Nav from "../components/nav";
import Application from "../components/application";
import styles from "../styles/Home.module.scss";
import About from "../components/about";
import Principles from "../components/principles";
import Projects from "../components/projects";
import Clients from "../components/clients";
import Why from "../components/why";
import Services from "../components/services";
import Main from "../components/main";

export default function Home() {
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    setTimeout(() => {
      setIsLoading(false);
    }, 5500);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>ИнструментЦентр</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/16x16.svg" />
      </Head>

      {isLoading ? (
        <Loading></Loading>
      ) : (
        <>
          <Nav></Nav>
          <Main></Main>
          <div className={styles.wrapper}>
            <div id="divAbout">
              <About></About>
              <Why></Why>
              <Principles></Principles>
            </div>

            <Services></Services>
            <Projects></Projects>
            <Clients></Clients>
            <Application></Application>
          </div>
        </>
      )}
    </div>
  );
}
